baseURL = "https://agora.jhutty.de/"
locale = "de"
title = "Agora"
theme = "cleanwhite"

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS"]

[params]
  [params.author]
    name = "Jhutty"

