baseURL = "https://agora.jhutty.de/"
locale = "de"
title = "Agora"
theme = "cleanwhite"

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS"]

[params]
  [params.author]
    name = "Jhutty"
    sidebar_about_description = "Philosoph, Autor, Analytiker"
    sidebar_avatar = "img/avatar.webp"


